# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Covid19Tracker
                                 A QGIS plugin
 This plugin tracks COVID19 live
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-11
        copyright            : (C) 2020 by Pawel Dzierzynski/The Map Workdhop
        email                : themapworkshop@gmail.com  
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Covid19Tracker class from file Covid19Tracker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Covid19_Tracker import Covid19Tracker
    return Covid19Tracker(iface)
